defaults:
  - environment@_global_: local
  - /features: full_cycle
  - override /hydra/launcher: joblib
  - _self_

hydra:
  mode: RUN
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
  job:
    chdir: false
  sweeper:
    params:
      target: SOH,RUL
      features: full_cycle #,full_cycle_no_temperature #,charge_only
  launcher:
    n_jobs: 4 # n_jobs for parallel hydra runs
