"""Default values for modeling pipeline configuration."""

from __future__ import annotations

DEFAULT_PROTOCOL_COLUMN = "charge_policy"
DEFAULT_FEATURE_HASH_MODE = "order_invariant"
DEFAULT_OBJECTIVE_TAU_GAP = 0.05
DEFAULT_OBJECTIVE_LAMBDA_GAP = 0.5
DEFAULT_CONFORMAL_ALPHA = 0.1
DEFAULT_CONFORMAL_CALIBRATION_PROPORTION = 0.2
DEFAULT_RANKING_N_REPEATS = 5
DEFAULT_RANKING_WEIGHT_RMSE = 0.7
DEFAULT_RANKING_WEIGHT_UNCERTAINTY = 0.3
DEFAULT_RANKING_CLIP_LOW_Q = 0.05
DEFAULT_RANKING_CLIP_HIGH_Q = 0.95
DEFAULT_TOPK_TAU_RMSE = 0.05
DEFAULT_TOPK_TAU_WIDTH = 0.10
DEFAULT_ARTIFACTS_REQUIRE_EXACT_MATCH = True
DEFAULT_ARTIFACTS_OVERWRITE = False
DEFAULT_WEIGHTING_STRATEGY = "none"
DEFAULT_SAMPLE_WEIGHT_N_BINS = 10
DEFAULT_LONG_LIFE_QUANTILE = 0.75
DEFAULT_LONG_LIFE_BOOST_FACTOR = 2.0
